[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mice = "B9xWniPBaNDGBDi1cxvTwFogiJtSEbZuuoqV2esqnyXp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/wangjin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
