[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_minter = "2dZCKmv4jwqCFKoT82yobCJqBcbp3FD4JZLLQXLqbNMK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wangjin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
